[[LAPACK]]
arch = "aarch64"
git-tree-sha1 = "b208399dedc3d8d789b3b9acd25544a019feaa01"
libgfortran_version = "5.0.0"
os = "macos"

    [[LAPACK.download]]
    sha256 = "f388ab87529835506f0de915260341a42a4483c396d8e3677edc9f02cb136b5e"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[LAPACK]]
arch = "aarch64"
git-tree-sha1 = "4787e0a85c05d905d126b0c4f5c6e164ce20f0ff"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK.download]]
    sha256 = "d2a5edb742a4856168e7c13dc59baa922266889f97d58f5014244ad128eeee2f"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[LAPACK]]
arch = "aarch64"
git-tree-sha1 = "8ea1a777d0d1be6c5674a8d15dccd8c56d58a01c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK.download]]
    sha256 = "fed17bedf59650b95226431c6eb8d667bda706c7838d73c2d63249473e782168"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[LAPACK]]
arch = "aarch64"
git-tree-sha1 = "60a8c718481a3fbb5cfee55cd0209484ae84529e"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[LAPACK.download]]
    sha256 = "239cc4f0e16fe9d9639ca9989bbbae5ff436c028255bf9db20e9a73badc638fb"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[LAPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "88b29b235e9d3285d54b58dd6ccaca7ea7debbd7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK.download]]
    sha256 = "310f33c945ffd3eaacba5b5a2b5c23e7809b53386737866639c8fbf9606fd825"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[LAPACK]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c3d5e963f89ad90a414ee059ef4c92c259d96e8c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK.download]]
    sha256 = "e443981e020ba0fca48ae399f8104b319bf83b798fe291e350f1cda27d45e80f"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[LAPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "69ca40cc1c37357539ec1fb27f57687c40c6a5e8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK.download]]
    sha256 = "06df3024f48d60a992416a5c44d58779d6ce25f0dd5c832d719abb09942a2f65"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[LAPACK]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fc3534f61bedb7fa27a2c875aed7279f0bc67ce5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK.download]]
    sha256 = "6e9bab334679a244f3c333468012d0031f66931287861e9e3aa96ceb93cf9f9f"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[LAPACK]]
arch = "i686"
git-tree-sha1 = "56bcb34506232b1b475a92c9138b4e3afccd4f3b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK.download]]
    sha256 = "8e63a256ad2e9a0682f6639806503d2125cb4b9b51ce8142b97764201370cd1e"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.i686-linux-gnu-libgfortran5.tar.gz"
[[LAPACK]]
arch = "i686"
git-tree-sha1 = "ee75dbc55ba046340fca668a62e4a1bc198521dc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK.download]]
    sha256 = "c1eadde95ba1690f47f4e2991c0342d6d2c53f1bbeff44532dc3091417bbdda2"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.i686-linux-musl-libgfortran5.tar.gz"
[[LAPACK]]
arch = "i686"
git-tree-sha1 = "857e68d23bba9cc72d21eba8da4d5305cbf8d07f"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAPACK.download]]
    sha256 = "327624181184dec4ea61b16070d3e2673ee064fe9817ea497cbcb080b6ad3638"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[LAPACK]]
arch = "powerpc64le"
git-tree-sha1 = "478922bdbf25aeed98748e44ccdc504ab8f9b869"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK.download]]
    sha256 = "9f971d614d3183189dbcd024317ce498fb078e427d1aa5427e5dfa958d064563"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[LAPACK]]
arch = "riscv64"
git-tree-sha1 = "414d6c63b0893feb0b5d3a66e92d97e8c11827f8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK.download]]
    sha256 = "1f54745e99947bbfe6413564f6be9473e53aee89482f878b51ac447bf63b8454"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.riscv64-linux-gnu-libgfortran5.tar.gz"
[[LAPACK]]
arch = "x86_64"
git-tree-sha1 = "19b0a44c95a290eaf5b6e396669a9f97ebf480d2"
libgfortran_version = "5.0.0"
os = "macos"

    [[LAPACK.download]]
    sha256 = "0b601e01bb30c5b562e19947fe0b467ce4c96703fcadba9fc58edffceebb8c29"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[LAPACK]]
arch = "x86_64"
git-tree-sha1 = "37745b955dcca39cf208ee3d98e52d54899b62be"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK.download]]
    sha256 = "3ef808ece6200acc99c68c7f34b6e91c1c64c8ea41fc2c8ca36ed0c0c39cdb69"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[LAPACK]]
arch = "x86_64"
git-tree-sha1 = "406eaebc0942a90013addc1a105228f8dde61ae7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LAPACK.download]]
    sha256 = "fe84457094f89166038103db6590f84ea922bbe17e30d5163687127e733fc942"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[LAPACK]]
arch = "x86_64"
git-tree-sha1 = "c77216d529ea1b422151cc3b07dbc912bd825e68"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[LAPACK.download]]
    sha256 = "54bad633ad95e01e073c556232b48fb1e161f6b3269315b90546d341ab3ef686"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[LAPACK]]
arch = "x86_64"
git-tree-sha1 = "2a33224c60dd019ee87d1c0c1992bea2284014b3"
libgfortran_version = "5.0.0"
os = "windows"

    [[LAPACK.download]]
    sha256 = "e55e6d6aa883aafd60cf008aae4f2f82cb59a7161655546a3e898f4619801f8e"
    url = "https://github.com/JuliaBinaryWrappers/LAPACK_jll.jl/releases/download/LAPACK-v3.12.1+1/LAPACK.v3.12.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
